[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/signup.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
